name: Build and test Go
on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build Go Binary
        run: CGO_ENABLED=0 GOOS=linux GOOARCH=arm go build -a -installsuffix cgo -o kube-plex_linux_arm

      - name: Log in to registry
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build -t recogio/kube-plex:${{ github.ref }} .

      - name: Deploy Docker Image
        run: docker push recogio/kube-plex:${{ github.ref }}
